name: Update Alpha Cyprus Streaming Url

on:
  schedule:
    - cron: '0 * * * *'  # This runs every hour; adjust as needed
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Run script to grab m3u8 URL
      run: |
        python /code/grab_m3u8.py

    - name: Commit and push m3u8 file
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add stream.m3u8
        git commit -m "Updated m3u8 URL"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
